### ISSUE TITLE
Issue finding blat from path

### ISSUE THREAD

**Issue by calchoo** [bcgsc/mavis#136]
## Error
Traceback (most recent call last):
  File "/gsc/pipelines/mavis/v2.0.0/venv/bin/mavis", line 11, in <module>
    load_entry_point('mavis==2.0.0', 'console_scripts', 'mavis')()
  File "/gsc/pipelines/mavis/v2.0.0/venv/lib/python3.6/site-packages/mavis-2.0.0-py3.6.egg/mavis/main.py", line 297, in main
    args.aligner_version = get_aligner_version(args.aligner)
  File "/gsc/pipelines/mavis/v2.0.0/venv/lib/python3.6/site-packages/mavis-2.0.0-py3.6.egg/mavis/align.py", line 152, in get_aligner_version
    raise ValueError("unable to parse blat version number from:'{}'".format(proc))
ValueError: unable to parse blat version number from:'/bin/sh: blat: command not found'

seems this export statement is wrong:
export PATH=/gsc/software/linux-x86_64/ucsc_tools/blat/blat:$PATH

**Comment by calchoo** [comment]
@morganbye The specific blat tool is set by the user. Its just the export statement puts the full path to it, instead of the directory, so bash can't find it.

**Comment by calchoo** [comment]
This has been fixed in v2.1.0
