### ISSUE TITLE
Mavis 2.1.0 failing at draw_sv_summary_diagram

### ISSUE THREAD

**Issue by marcus-carreira** [bcgsc/mavis#140]
## Expected Behaviour
Here is a batch that finished properly with a MAVIS-<job_id>.COMPLETE.

/projects/trans_scratch/mavis/gd-P02854_gn-P02856_rd-P02857/mavis_v2.1.0/222/P02854_diseased_genome/annotate/batch-sSFjTsJvGJ58ftquUpKDt3-1

## Actual Behaviour
3 of the batch files failed. I tried to resubmit and saw which job array failed:

```
[mcarreira@mcarreira01 222]$ /gsc/pipelines/mavis/v2.0.0/bin/mavis schedule -o /projects/trans_scratch/mavis/gd-P02854_gn-P02856_rd-P02857/mavis_v2.1.0/222 --submit
                      MAVIS: 2.0.0
                      hostname: mcarreira01.phage.bcgsc.ca
[2018-07-17 10:53:42] arguments
                        command = 'schedule'
                        log = None
                        log_level = 'INFO'
                        output = '/projects/trans_scratch/mavis/gd-P02854_gn-P02856_rd-P02857/mavis_v2.1.0/222'
                        resubmit = False
                        submit = True
[2018-07-17 10:53:45] validate
                        MV_P02856_batch-sSFjTsJvGJ58ftquUpKDt3 (1861838) is COMPLETED
                          100 tasks are COMPLETED
                          run time: 17743
                        MV_P02857_batch-sSFjTsJvGJ58ftquUpKDt3 (1861839) is COMPLETED
                          54 tasks are COMPLETED
                          run time: 3466
                        MV_P02854_batch-sSFjTsJvGJ58ftquUpKDt3 (1861840) is COMPLETED
                          100 tasks are COMPLETED
                          run time: 22731
[2018-07-17 10:54:01] annotate
                        MA_P02856_batch-sSFjTsJvGJ58ftquUpKDt3 (1861841) is COMPLETED
                          100 tasks are COMPLETED
                          run time: 3311
                        MA_P02857_batch-sSFjTsJvGJ58ftquUpKDt3 (1861842) is COMPLETED
                          54 tasks are COMPLETED
                          run time: 617
                        MA_P02854_batch-sSFjTsJvGJ58ftquUpKDt3 (1861843) is FAILED
                          97 tasks are COMPLETED
                          3 tasks are FAILED
[2018-07-17 10:54:10] pairing
                        MP_batch-sSFjTsJvGJ58ftquUpKDt3 (1861844) is PENDING
[2018-07-17 10:54:10] summary
                        MS_batch-sSFjTsJvGJ58ftquUpKDt3 (1861845) is PENDING
                      rewriting: /projects/trans_scratch/mavis/gd-P02854_gn-P02856_rd-P02857/mavis_v2.1.0/222/build.cfg
```

Here is the path to the output and the batches that failed:

/projects/trans_scratch/mavis/gd-P02854_gn-P02856_rd-P02857/mavis_v2.1.0/222/

/projects/trans_scratch/mavis/gd-P02854_gn-P02856_rd-P02857/mavis_v2.1.0/222/P02854_diseased_genome/annotate/batch-sSFjTsJvGJ58ftquUpKDt3-28

/projects/trans_scratch/mavis/gd-P02854_gn-P02856_rd-P02857/mavis_v2.1.0/222/P02854_diseased_genome/annotate/batch-sSFjTsJvGJ58ftquUpKDt3-29

/projects/trans_scratch/mavis/gd-P02854_gn-P02856_rd-P02857/mavis_v2.1.0/222/P02854_diseased_genome/annotate/batch-sSFjTsJvGJ58ftquUpKDt3-30

This is the traceback for each of the log files:
```
Traceback (most recent call last):
  File "/gsc/pipelines/mavis/v2.1.0/venv/bin/mavis", line 11, in <module>
    load_entry_point('mavis==2.1.0', 'console_scripts', 'mavis')()
  File "/gsc/pipelines/mavis/v2.1.0/venv/lib/python3.6/site-packages/mavis-2.1.0-py3.6.egg/mavis/main.py", line 414, in main
    raise err
  File "/gsc/pipelines/mavis/v2.1.0/venv/lib/python3.6/site-packages/mavis-2.1.0-py3.6.egg/mavis/main.py", line 373, in main
    annotate_main.main(**args, start_time=start_time)
  File "/gsc/pipelines/mavis/v2.1.0/venv/lib/python3.6/site-packages/mavis-2.1.0-py3.6.egg/mavis/annotate/main.py", line 254, in main
    drawing, legend = draw(drawing_config, ann, reference_genome.content, template_metadata.content, drawings_directory)
  File "/gsc/pipelines/mavis/v2.1.0/venv/lib/python3.6/site-packages/mavis-2.1.0-py3.6.egg/mavis/annotate/main.py", line 51, in draw
    **other_settings
  File "/gsc/pipelines/mavis/v2.1.0/venv/lib/python3.6/site-packages/mavis-2.1.0-py3.6.egg/mavis/illustrate/diagram.py", line 245, in draw_sv_summary_diagram
    reference_genome=reference_genome
  File "/gsc/pipelines/mavis/v2.1.0/venv/lib/python3.6/site-packages/mavis-2.1.0-py3.6.egg/mavis/illustrate/elements.py", line 364, in draw_ustranscript
    end=genomic_max
  File "/gsc/pipelines/mavis/v2.1.0/venv/lib/python3.6/site-packages/mavis-2.1.0-py3.6.egg/mavis/illustrate/util.py", line 163, in generate_interval_mapping
    if start < intervals[0].start:
IndexError: list index out of range
```

## Steps to Reproduce the Behaviour

Resubmitting using the same submit script in 

/projects/trans_scratch/mavis/gd-P02854_gn-P02856_rd-P02857/mavis_v2.1.0/222/

**Comment by marcus-carreira** [comment]
The bugfix has solved the issue.
