### ISSUE TITLE
Ignore reads that have unmapped maps when gathering flanking evidence

### ISSUE THREAD

**Issue by calchoo** [bcgsc/mavis#158]
## Actual Behaviour
```
Traceback (most recent call last):
  File "/gsc/pipelines/mavis/v2.1.1/venv/bin/mavis", line 11, in <module>
    load_entry_point('mavis==2.1.1', 'console_scripts', 'mavis')()
  File "/gsc/pipelines/mavis/v2.1.1/venv/lib/python3.6/site-packages/mavis-2.1.1-py3.6.egg/mavis/main.py", line 414, in main
    raise err
  File "/gsc/pipelines/mavis/v2.1.1/venv/lib/python3.6/site-packages/mavis-2.1.1-py3.6.egg/mavis/main.py", line 371, in main
    validate_main.main(**args, start_time=start_time)
  File "/gsc/pipelines/mavis/v2.1.1/venv/lib/python3.6/site-packages/mavis-2.1.1-py3.6.egg/mavis/validate/main.py", line 159, in main
    evidence.load_evidence(log=LOG)
  File "/gsc/pipelines/mavis/v2.1.1/venv/lib/python3.6/site-packages/mavis-2.1.1-py3.6.egg/mavis/validate/base.py", line 865, in load_evidence
    self.collect_flanking_pair(flanking_read, mate)
  File "/gsc/pipelines/mavis/v2.1.1/venv/lib/python3.6/site-packages/mavis-2.1.1-py3.6.egg/mavis/validate/base.py", line 345, in collect_flanking_pair
    raise ValueError('input reads must be a mapped and mated pair. One or both of the reads is unmapped')
ValueError: input reads must be a mapped and mated pair. One or both of the reads is unmapped
```

**Comment by calchoo** [comment]
Reads causing the issue:
```
HS23_110:5:1109:4945:69202	167	22	41360058	60	66M9S	=	41368474	8491	CCCCBEDGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEEFGGGGGGGGGGG<B/CGGGGGGGGGGGGGGGBG	X0:i:1	X1:i:0	MD:Z:66	PG:Z:MarkDuplicates	RG:Z:176944	XG:i:2	AM:i:23	NM:i:0	SM:i:37	XM:i:0	XN:i:-6	XO:i:1	XT:A:U
HS23_110:5:1109:4945:69202	83	22	41368474	60	75M	=	41360058	-8491	GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFEGGGGGGGGGGGGGGGGGGGGGCGGGGEGGGGBBBBB	X0:i:1	X1:i:4	XA:Z:22,-52583960,75M,4;22,-52135119,75M,4;22,-52134136,75M,4;22,-52134440,75M,4;	MD:Z:1T1C1G69	PG:Z:MarkDuplicates	RG:Z:176944	XG:i:0	AM:i:23	NM:i:3	SM:i:23	XM:i:3	XO:i:0XT:A:U
```
