### ISSUE TITLE
clustering producing invalid rearrangement

### ISSUE THREAD

**Issue by calchoo** [bcgsc/mavis#189]
### OS: Centos 6

# Error
```
                      loading: /projects/wtss_scratch/mavis/POG/POG669/gd-P01759_gn-P01768_rd-P01763/mavis_v2.2.4/2010/P01759_diseased_genome/cluster/batch-TChGqiE6dfozYTTPbLwGMA-77.tab
Traceback (most recent call last):
  File "/gsc/pipelines/mavis/v2.2.4/venv/bin/mavis", line 11, in <module>
    load_entry_point('mavis==2.2.4', 'console_scripts', 'mavis')()
  File "/gsc/pipelines/mavis/v2.2.4/venv/lib/python3.6/site-packages/mavis-2.2.4-py3.6.egg/mavis/main.py", line 414, in main
    raise err
  File "/gsc/pipelines/mavis/v2.2.4/venv/lib/python3.6/site-packages/mavis-2.2.4-py3.6.egg/mavis/main.py", line 371, in main
    validate_main.main(**args, start_time=start_time)
  File "/gsc/pipelines/mavis/v2.2.4/venv/lib/python3.6/site-packages/mavis-2.2.4-py3.6.egg/mavis/validate/main.py", line 86, in main
    cast={COLUMNS.cluster_id: lambda x: str(uuid()) if not x else x}
  File "/gsc/pipelines/mavis/v2.2.4/venv/lib/python3.6/site-packages/mavis-2.2.4-py3.6.egg/mavis/util.py", line 245, in read_inputs
    **kwargs
  File "/gsc/pipelines/mavis/v2.2.4/venv/lib/python3.6/site-packages/mavis-2.2.4-py3.6.egg/mavis/util.py", line 531, in read_bpp_from_input_file
    raise InvalidRearrangement('could not produce a valid rearrangement', row)
mavis.error.InvalidRearrangement: ('could not produce a valid rearrangement', {'tracking_id': 'manta-MantaDEL:175574:0:0:0:0:0;strelka-8YtWsuCjhNRzCL2GN5pdbd', 'library': 'P01759', 'cluster_id': 'GicQ9HpSNkSQZ7woPVDYo2', 'cluster_size': '2', 'event_type': 'deletion', 'break1_chromosome': '15', 'break1_position_start': 67333604, 'break1_position_end': 67333604, 'break1_orientation': 'L', 'break1_strand': '?', 'break1_seq': None, 'break2_chromosome': '15', 'break2_position_start': 67333605, 'break2_position_end': 67333605, 'break2_orientation': 'R', 'break2_strand': '?', 'break2_seq': None, 'opposing_strands': False, 'stranded': False, 'protocol': 'genome', 'disease_status': 'diseased', 'tools': 'manta;strelka', 'untemplated_seq': None, 'BND_DEPTH': None, 'CIGAR': None, 'CONSENSUS': None, 'EVENT': None, 'Germline': None, 'HOMLEN': None, 'HOMSEQ': None, 'IC': None, 'IHP': None, 'IMPRECISE': None, 'INV3': None, 'INV5': None, 'JUNCTION_QUAL': None, 'JUNCTION_SOMATICSCORE': None, 'LEFT_SVINSSEQ': None, 'MAPQ': None, 'MATEID': None, 'MATE_BND_DEPTH': None, 'NT': None, 'OVERLAP': None, 'PE': None, 'PRECISE': None, 'QSI': None, 'QSI_NT': None, 'Quality': None, 'RC': None, 'RIGHT_SVINSSEQ': None, 'RU': None, 'SGT': None, 'SOMATIC': None, 'SOMATICSCORE': None, 'SR': None, 'SRQ': None, 'SVINSLEN': None, 'SVINSSEQ': None, 'SVLEN': None, 'SVMETHOD': None, 'Somatic': None, 'TQSI': None, 'TQSI_NT': None, 'id': None, 'line_no': 365, 'tag': None, 'transabyss_gene': None, 'transabyss_genes': None})
```

# original inputs
```
Manta
15	67333523	MantaDEL:175574:0:0:0:0:0	GGAAGGAAGGAAAAGGGAAGGGAAGGTAGAGAAGGAAGGAAAAGGGAAGGGAAGGTAGA	G	89	MinGQ	END=67333581;SVTYPE=DEL;SVLEN=-58;CIGAR=1M58D;CIPOS=0,96;HOMLEN=96;HOMSEQ=GAAGGAAGGAAAAGGGAAGGGAAGGTAGAGAAGGAAGGAAAAGGGAAGGGAAGGTAGAGAAGGAAGGAAAAGGGAAGGGAAGGTAGAGAAGGAAGG	GT:FT:GQ:PL:PR:SR	0/1:MinGQ:3:139,3,0:0,0:0,4

Strelka
15	67333623	.	AGG	A	.	QSI_ref	IC=1;IHP=4;NT=ref;QSI=12;QSI_NT=12;RC=3;RU=G;SGT=ref->het;SOMATIC;TQSI=2;TQSI_NT=2	DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50	17:17:18,18:0,0:0,0:22.68:0.03:0.00	40:40:28,30:6,6:8,8:41.77:3.90:0.00
```
# converted inputs
```
manta-MantaDEL:175574:0:0:0:0:0	deletion	15	67333523	67333619	L	?	None	15	67333581	67333581	R	?	None	False	False	manta		None	1M58D	None	96	GAAGGAAGGAAAAGGGAAGGGAAGGTAGAGAAGGAAGGAAAAGGGAAGGGAAGGTAGAGAAGGAAGGAAAAGGGAAGGGAAGGTAGAGAAGGAAGG	None	None	None	None	None	None	None	None	None	None	None	None	None	-58	MantaDEL:175574:0:0:0:0:0
strelka-8YtWsuCjhNRzCL2GN5pdbd	deletion	15	67333623	67333623	L	?	None	15	67333625	67333625	R	?	None	False	False	strelka		1	4	ref	None	12	12	3	G	ref->het	True	2	2
```

# Clustering output
```
manta-MantaDEL:175574:0:0:0:0:0;strelka-8YtWsuCjhNRzCL2GN5pdbd		sDpE4no2SeREAdspcg4zZU	2	deletion	15	67333604	67333604	L	?	None	15	67333605	67333605	R	?	None	False	False	genome	normal	manta;strelka	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None
```

**Comment by creisle** [comment]
related PR https://github.com/bcgsc/mavis/pull/194
